treehousedev/treehouse

- web/pages/index2.tsx
updated some of the placeholder text on the website.
> website: text updates

- web/layouts/docs.tsx
- web/pages/docs/user.md
- web/static/style/design.css
* integrated "getting started" docs
* more tweaks to typography (using https://practicaltypography.com/space-between-paragraphs.html)
* updated sidebar nav for user guide
> website: more doc and typography updates

- web/pages/docs/project.md
added links to github issues/forum
some formatting fixes and editing for clarity
> web: minor updates to project docs

- web/layouts/default.tsx
Otherwise a local version takes you to the online demo.
> Make "demo" link relative

- lib/ui/app.tsx
- web/static/app/main.css
- web/static/style/design.css
closes #90 
move most of the inline styles in app.tsx into main.css
> app: move app.tsx inline styles to CSS

- web/static/style/site.css
primarily increased the line height overall, and balanced some of the margins.
> web: tweak typography on blog and docs

- lib/ui/outline.tsx
- lib/ui/panel.tsx
- web/static/app/main.css
- web/static/style/design.css
closes #91 
updated/simplified some styles but mostly just moved things over to CSS.
> Move panel and outline styles to css

- lib/ui/palette.tsx
- web/static/app/main.css
> add palette styles to css and match styles to search bar

- lib/ui/menu.tsx
- web/static/app/main.css
- web/static/style/design.css
> add inline menu styles to css and match styles to search bar and palette

- lib/ui/palette.tsx
Changes the filter to do a case insensitive startsWith search on the command title.
> ui: updated command palette to do case insensitive title filter

- lib/ui/palette.tsx
- Adds a click handler
- Sets the selected item to 0 on component creation
> ui: added click handlers to commands in command palette

- web/static/app/main.css
finishing up https://github.com/treehousedev/treehouse/pull/139
> also make new nodes have a transparent background for ease of theming

- web/static/app/main.css
one last input bg to make transparent for theming
> Last transparent input

- lib/view/list.tsx
> view: use refTo node in list view if it exists

- lib/ui/outline.tsx
Added a new function in the component that determines if the handle should be shown.
> ui: fixed how handles are conditionally hidden/shown

- lib/ui/node/new.tsx
- lib/ui/outline.tsx
- web/static/app/main.css
- web/static/style/design.css
This adds all of the color variables and a single font variable to control the font type. Opting to leave out other font styles like size and weight for now.
> Implement CSS Variables

- web/static/app/main.css
* create a firmer definition between icons and secondary icons and assign icons in the app accordingly
* add variables for nav icons and nav labels to make theming a little more fun
color-nav-label is a semantic label like color-sidebar-background, i think it is okay since these are specific to the UI and not part of a broader pattern (yet).
> add variables for icons and navigation labels

- lib/mod.ts
> lib: prevent turning nodes with children into search nodes

- lib/ui/palette.tsx
- web/static/app/main.css
> ui: add keyboard shortcuts to command palette

- lib/view/list.tsx
> view: hide new node component on nodes with fields

- lib/mod.ts
> lib: fix backspace behavior on fields

- web/pages/index.tsx
> website: update treehouse homepage to include live search and fields as features

- web/static/app/main.css
> Mobile app: Increase size of node handle and menu to improve tap sizes

- lib/ui/outline.tsx
> ui: prevent deletion of parent nodes

- lib/ui/app.tsx
- lib/ui/palette.tsx
- lib/ui/picker.tsx
- lib/ui/search.tsx
- lib/workbench/workbench.ts
- web/static/app/main.css
consolidate search and command palette style and logic into picker. makes search into a dialog so it can be used like a standalone dialog in mobile. overall, cleans things up and improves interaction a bit (mouse cursor is set to pointer over "items" and hover will set them to selected).
@taramk
> ui: picker

- web/static/app/main.css
> remove bottom padding on mobile navbar

- lib/mod.ts
> lib: collapse children when switching to table view

- lib/ui/notices.tsx
> Update modals to use menu icon instead of settings icon

- lib/mod.ts
> lib: prevent outdenting a top level node

- web/static/app/main.css
> ui: fix scrollbar in tabs view

- web/docs/user.md
> web: add docs for tags and templates

- lib/mod.ts
- web/static/app/main.css
- title case for a couple palette commands
- make drawer width same as sidebar width
- change animation to faster cubic bezier
- minor tweaks to make text fit in narrower sidebar
> ui: minor tweaks to drawer styles etc

- web/demo/index.njk
closes #272. separate ticket for treestar.
also removed rubik.
verified that italics are correct in app.
> ui: add italics to treehouse app

- web/static/app/main.css
closes #259 
info from https://stackoverflow.com/questions/25066214/flexbox-not-giving-equal-width-to-elements
> ui: add flex-basis so panels are equal width

- web/static/style/themes/sublime.css
closes #284 
passes AA contrast standards
> ui: update sublime-pink variable to pass contrast standards and be less blinding

- web/static/style/themes/sublime.css
uhhh don't really know how to test this but it looks right!
> ui: add sublime font

- lib/ui/node/editor.tsx
This PR adds a new onpaste handler to the `TextAreaEditor` component. It splits the clipboard data by newline, adds the first line using the passed in `setter`, and then loops though any remaining lines. At first, I had the loop call `executeCommand("insert", ...)`, but I needed a reference to the newly created node to continue the loop, so it's done more manually.
Let me know what you think.
Closes #250
> lib: handle onpaste and create new nodes for each line

- lib/com/description.tsx
- lib/mod.ts
- lib/ui/node/editor.tsx
- web/static/app/main.css
> descriptions and prevent multiple checkboxes

- web/index.tsx
> Added alt tag to main image on homepage for better
