web/pages/docs/quickstart.md, web/static/style/design.css, web/static/style/site.css
* update code editor styles (padding and colors)
* change all headers to 700 weight (after looking at them for awhile they started to feel too heavy)
(at some point i will make a dark mode color palette for the code editor, but i could spend days on that so for now i'm borrowing colors from the VS code Nite Owl theme)
=> web: code editor styles, remove 800 and 900 weight

web/static/app/main.css
closes #99 
i think. there's a hack in there (line height 0.95) to make the descenders (g, p, etc.) not get cut off at the bottom. i can't figure out a better way to do it. but it gets the job done in the meantime.
=> app: fix title node styling issue

lib/ui/quickadd.tsx, web/static/app/main.css
=> add quick add inline styles to css, match other modals/notices

lib/ui/search.tsx, web/static/app/main.css
closes #103 
this isn't the complete list of changes i wanted to make, only the things i can do myself. will make a separate wishlist ticket for everything else. mainly adding easy interactions for the sidebar and node menu.
=> initial mobile style updates

lib/workbench/workspace.ts
Changes the `expanded` map import process to only import the nodes that exist in the workspace by calling `bus.find` for each one.
=> lib: only import node keys that exist in workspace

lib/mod.ts
The PR is really the addition of two lines: 208 and 229. The rest is spacing changes automatically applied by Sublime Text. 
This stops the Indent and Outdent commands from doing anything if the node is a Field.
Note: Eventually those commands should probably be disabled when the palette is opened while on a Field.
=> lib: prevent indenting/outdenting a field node

lib/ui/panel.tsx
Relevant line: 43.
Just used '&nbsp;' instead of '/'.
=> ui: use a space instead of a slash in the top navbar

web/static/app/main.css
fixes #87 
focused on aligning the text w/ the search text, setting a negative margin seems like the only way to fix it. and yes chrome is literally a 1px difference but i can tell 😆
=> tiny hack to fix vertical label alignment

lib/ui/outline.tsx, web/static/app/main.css, web/static/style/design.css
* make sure all of the node handle icons are the same color + accent color (created variables)
* centralize those styles by replacing inline colors with "currentColor" so .node-handle can define all of them
=> Centralize node icon colors in CSS

web/static/app/main.css
causes a misalignment issue in the topbar when setting a different font (sublime custom theme, default monospace font), and it doesn't seem to be doing anything anyway so i removed it.
=> Remove line height because it doesn't do anything

lib/ui/outline.tsx
This is for #31 
This toggles between display: none or block depending on if `node.name` is empty or not. There might be a better way to do this. Maybe using a nbsp or a blank icon (with a little width) instead of hiding the entire handle would make sense.
I considered trying to do something conditional in `handleIcon` on TextField, but it doesn't look like the component holds the node data itself so it didn't seem like it would work.
=> ui: hide node handle when name is empty

lib/com/search.tsx, lib/mod.ts, lib/ui/node/editor.tsx, lib/ui/outline.tsx
Closes #134 
This makes the changes suggested in the issue. I added a `handlePlaceholder` method to `SearchNode`, leaving the possibility for any Node type to do something with its placeholder text. The way I'm calling it in lib/ui/outline.tsx isn't consistent with the way it's called in the rest of the component, but I wasn't sure of the best way to have `placeholder` be available for the check on L160. That check (to decide whether to show the handle or not) was added because it looked weird when the placeholder was showing, but the handle wasn't.
I feel like there might be a better way of doing this so let me know what you think.
=> ui: added some placeholder handling and changed search node ui

lib/mod.ts
=> lib: prevent collapsing parent node on outdent when fields exist

lib/com/search.tsx, lib/ui/outline.tsx
This adds a `collapsed` arg to `handleIcon` so the background indicator can be shown. So far, these kinds of decisions were made in the outline component, so let me know if you're ok with this change.
Also, I ended up doing a nested svg just so I can easily control the size/position of the inner search icon.
By the way, I considered adding the `subCount(node) > 0 && !expanded` logic to its own function, but it felt awkward when I did. But let me know if you would rather it not be repeated twice.
Closes #150
=> lib: update search node icon handler to show collapsed state

web/static/app/main.css
a little hurt that you didn't tell me you thought we needed a shadow. anyway, i tweaked it to make it a little more subtle w/ a more realistic light source.
also, using a nearly-transparent black will be more versatile for custom themes.
before and after:
=> update dialog shadow

lib/com/search.tsx, lib/ui/outline.tsx
closes #188 
* make node outer circles the same consistent size
* increase size/stroke of search icon for legibility
* update reference node to match
i guess these should all use the same style, but i barely understand how this svg sizing stuff works so i'm not sure how to do that. should it be a CSS class? or a single element in the code? some of the icons may need to be sized/aligned by hand within a frame, but the outer circle should always be the same.
Before and after:
=> tweak sizing of node outer circles and icon

lib/ui/app.tsx, lib/ui/search.tsx, web/static/app/main.css, web/static/style/design.css
closes #198 
* add padding around sidebar and panels
* increase body font size and nav/secondary font size
* center dialogs horizontally (user menu, node menu, search)
* move sidebar inline styles to CSS
there will be more tweaks coming but this is a good first step to make the tap areas a better size and create some structure in the mobile CSS styles.
=> pass at updating mobile styles/sizing

web/static/style/themes/darkmode.css
the purple had terrible contrast with the dark background, doing white for now. we only use the primary color for the primary button on modals at the moment.
=> fix dark mode primary color

lib/ui/app.tsx
This ignores the special keys (control, shift, alt, meta) themselves instead of any keys with those modifiers set.
Fixes #217 
@taramk
=> lib: ignore control, shift, alt, meta keys

lib/ui/notices.tsx, lib/ui/quickadd.tsx, lib/ui/settings.tsx, web/static/app/main.css
This replaces all forms with class `notice` to divs, and adds some padding to the class.
Closes #201
=> ui: replace forms with divs

lib/mod.ts
Closes #175 
@taramk : The figma docs show an "external link" icon next to the word Documentation, but I noticed none of the other links have icons, so I didn't try to put it in. Let me know if you want me to add icons to this and the "Submit Issue" links.
=> lib: add link to documentation

lib/backend/browser.ts
Fixes #197 
By default, `MiniSearch` searches all of the words in the query independently, which means a search for something like 'sweet thai' searches for any matches (including in all Node fields) for either the words 'sweet' or 'thai'. It seems to make the search results too broad. This changes the search options to include `combineWith: 'AND'`, which narrows the results.
I'm not sure if this goes too far in the other direction though. Let me know @taramk
=> lib: use combineWith when searching

lib/com/tag.tsx, web/static/app/main.css
closes #230 
uses existing theme variables in a way that ensures the best contrast
=> update tag colors to use theme variables

lib/view/table.tsx, web/static/app/main.css
Closes #210 
This adds padding to the front of the `:first-child` th element in the table (for the "Title" text alignment) to match the width and padding of the handles in the elements below. It would be nice if it wasn't just a hardcoded px width (so we don't have to remember to change it if the handle sizes change), but I don't know of a better way of doing it yet. Let me know what you think @taramk
=> ui: improve table view styling

lib/com/tag.tsx, web/static/app/main.css
* swap out tag icon for hashtag
* make hashtag color slightly lower contrast (use secondary icon variable, works for all themes)
* make tag text slightly smaller in size (tags are secondary information and should be visually treated as such)
=> swap out svg for hashtag, minor style updates

web/blog/v0-3-0.md, web/blog/v0-4-0.md, web/blog/v0-5-0.md, web/docs/user.md, web/index.tsx
closes #248 
replaced all names except 0.3.0 where i added a note about the name change, because we refer to it as Live Search in the demo video and i didn't want that to be confusing
=> change all instances of live search to smart nodes

lib/mod.ts
should go to user guide rather than just docs (which links to quick start)
closes #241
=> Update docs link in app

lib/action/commands.ts, lib/com/tag.tsx, lib/mod.ts, lib/ui/palette.tsx
Fixes #242 
- Adds a `hidden` attribute to `Command`. This was mentioned in the ticket and seemed better than maintaining a list of ids to filter
- Uses a regex to help with title case: `/(^|\s)\S/g` (first letter after whitespace or the beginning of a line)
- Sorts everything in the command palette no matter what. Let me know if it looks good @taramk
=> lib: clean up command palette commands

lib/ui/panel.tsx
When hitting the back button in a panel, there may be a duplicate node id in the path. This change `pop`s again if the node is still in the path, which fixes having to click the button twice.
I started looking into why this is happening the in the first place, but I haven't figured it out yet. I thought it might help to make a command for the "back" behavior and add this there (and maybe also set `workspace.lastOpenedID` too?), but I didn't know if that made sense to do before figuring out what the actual problem is first. Anyway, I thought I should get this small change out for review now. Let me know what you think @progrium
=> lib: compensate for duplicate nodes in path

lib/mod.ts, lib/ui/outline.tsx, web/static/app/main.css
This adds a new `cut` attr to nodes when they're cut, and adds a `cut-node` class that sets display to none.
@taramk let me know how you feel about it.
Closes #274
=> Remove cut nodes from view

lib/ui/node/new.tsx
Fixes #275 
This one is kinda tricky. The ticket says the issue is with pasting into a new node. Here's what I did in my testing:
1. Copy a node
2. Open (`zoom` command) an existing node with no children
3. Hit Command + K (`pick-command` command)
The last step fails.
Reason:
Opening a node with no children shows a panel with a `NewNode` as the body. The `NewNode` doesn't exist in the workspace yet. The actual node isn't created until a character is entered (`oninput`). Pressing Command + K doesn't count as `oninput`, so when the `pick-command` action is run, it sees that there's no node in context, and as a backup, it tries to set the context to the current path head. After `zoom` though, the path head isn't on the screen any more, so it crashes since the input control it's expecting …
=> lib: insert child on new node keydown

lib/workbench/workbench.ts
Closes #277 
Honestly, I don't fully understand this issue. The way the code was written, it should already support both field keys and values containing spaces. But during testing, I noticed something weird. The example Smart Node I made for testing used the following search:
`"travel by":car`
According to a console log, `fieldQuery` contained the object: `{"travel by": "car"}`
During the `for (const f in fieldQuery)` loop, `f` is a string that contained escaped quotes. (example: `"\"travel by\""`). The keys in `fields` didn't. I'm not sure why that's happening, but this change fixes it.
I'll put this out for review, but I'll continue investigating to better understand what's going on.
=> lib: support spaces in field key search

lib/mod.ts
Fixes #293 
In some circumstances, the logic that hides a cut node will also hide a newly pasted node. This is because the node stays in the clipboard after pasting. This PR clears the clipboard after a paste. It solves the issue in the ticket, but it also means you **can't paste a node more than once** (you would have to cut/copy again to paste that node again).
I'm not sure if that's acceptable, so let me know if not and I'll figure out a different fix @taramk
=> lib: clear clipboard on paste
